### ISSUE TITLE
lowerCaseAllColumnNames option in extra_config

### ISSUE THREAD

**Issue by josesydor** [AnatolyUss/nmig#130] opened 2024-08-27 18:48 UTC
Hi there,
First of, thank you for this tool, it's going to save me a lot of time.

But I need to figure out how to properly add lowerCaseAllColumnNames : true inside  extra_config.json as it is not documented.

I tried to simply change ExtraConfigProcessor.ts with:
`retVal = retVal.toLowerCase(); `

That indeed changed the column names to lowercase, but the tables didn't get populated because the insert sees them with the old names still:
	--[populateTable] Error loading table data:
_

> SELECT `Id` AS `Id`,REPLACE(`Label`, ' ', '') AS `Label`,`Order` AS `Order`,`AboutProductInformationStyle` AS `AboutProductInformationStyle` FROM `aboutproductinformation`;

_

Can I get some help, please?

**Comment by AnatolyUss** [comment] 2024-08-27 21:12
Hi Jose,
Sure, with pleasure!

Try following, via config:
1. At ``config.json``, set ``enable_extra_config: true``
2. At ``extra_config.json``, add ``lowerCaseAllColumnNames: true`` at the root of the document.
3. Run ``nmig`` as usual.

**Comment by josesydor** [comment] 2024-08-28 11:30
Hi Anatoly,
Thank you for the quick reply. The column names are lowercase alright due to the extra_config, but no data was inserted. I still get this error:

```
	--[populateTable] Error loading table data:
SELECT `Id` AS `Id`,REPLACE(`Label`, ' ', '') AS `Label`,`Order` AS `Order`,`AboutProductInformationStyle` AS `AboutProductInformationStyle` FROM `aboutproductinformation`;
```

**Comment by AnatolyUss** [comment] 2024-08-30 20:06
Jose, hello again,
I think, the issue is fixed now.

1. Please, either ``git pull`` the latest changes from ``master``, or download the latest release ``v6.1.1``.
2.  At ``config.json``, set ``enable_extra_config`` to ``true``.
3. At extra_config.json, find the ``lowerCaseAllColumnNames``, and set it ``true``.
4. Run ``nmig`` as usual.

Please, let me know if the issue is resolved on your side.

**Comment by josesydor** [comment] 2024-08-31 13:10
I confirm it worked. Thank you kindly!
Also confirm changing datatypes mapping default worked, as I had to use citext for varchars and map bit to bool because, you know, in MariaDB/MySQL Bit(1) and Boolean are used interchangeably but, in PG, you cannot do, say: `WHERE NOT (isSomething)` with bit datatypes (varying or not), only Bool

**Comment by AnatolyUss** [comment] 2024-09-01 04:27
Great, glad it worked!
Thank you, Sir!

**Closed** 2024-09-01 20:56 UTC
