### ISSUE TITLE
Infinite loop "loading the data"

### ISSUE THREAD

**Issue by snblitz** [AnatolyUss/nmig#57] opened 2019-03-14 00:46 UTC
Cool tool.  Just gave it a try.  It seems to work fine, but looks to be in an infinite loop.
The data looks to have successfully transferred in a few minutes but for some hours now it continues to print to the screen:
 --[loadData] Loading the data... 
 --[loadData] Loading the data...

**Comment by snblitz** [comment] 2019-03-14 00:48
root@mysqlrdsbridge:~/src/nmig# nodejs --version
v10.15.3

**Comment by AnatolyUss** [comment] 2019-03-14 06:48
Hi,
Could you send me the error log file (zipped)?
It should be under /nmig/logs_directory/errors-only.log
Thanks

**Comment by snblitz** [comment] 2019-03-15 19:56
The file you requested does not exist.

Here is the output of npm start

d...
	--[TableProcessor::createTable] Table "kayako"."swusernotedata" is created...
	--[TableProcessor::createTable] Table "kayako"."swusernotes" is created...
	--[TableProcessor::createTable] Table "kayako"."swusers" is created...
	--[TableProcessor::createTable] Table "kayako"."swusersettings" is created...
	--[TableProcessor::createTable] Table "kayako"."swuserproperties" is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitornotedata" is
created...
	--[TableProcessor::createTable] Table "kayako"."swvisitornotes" is created...
	--[TableProcessor::createTable] Table "kayako"."swuserverifyhash" is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitorbans" is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitordata" is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitorgroups" is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitorfootprints"
is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitorpulls2" is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitorruleactions"
is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitorpulls" is created...
	--[TableProcessor::createTable] Table
"kayako"."swvisitorrulecriteria" is created...
	--[TableProcessor::createTable] Table "kayako"."swvisitorrules" is created...
	--[TableProcessor::createTable] Table "kayako"."swwidgets" is created...
	--[DataPoolManager.readDataPool] Data-Pool is loaded...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...
	--[loadData] Loading the data...

The loading the data will go on forever until I control-c the process.

--
brian

**Comment by AnatolyUss** [comment] 2019-03-20 15:31
Unfortunately I failed to reproduce the bug.
Have all tables been migrated?
Do you lack any data after migration?

**Comment by snblitz** [comment] 2019-03-20 20:41
So far as I can tell, all the data transfers.
The program then remains in an infinite lookup repeating "loading the data".
Has been doing so for 3 days now.
I will try another transfer from scratch and report back.

**Comment by Boshen** [comment] 2019-03-21 07:06
I'm also getting this.
Out of 304761 rows, it stopped at 303318 rows. In DataLoader, signal.chunks.length is giving me 0 so it infinite looped. Can you guide me on where the data/message is sent from so I can debug further?

**Comment by snblitz** [comment] 2019-04-11 19:09
I had to time to try the transfer again.  All proceeded as last time eventually ending in an infinite loop:

        --[pipeData]  For now inserted: 6639 rows, 
                Total rows to insert into "kayako"."swescalationpaths": 6639
        --[loadData] Loading the data...
        --[pipeData]  For now inserted: 150871 rows, 
                Total rows to insert into "kayako"."swbayeswords": 150871
        --[pipeData]  For now inserted: 22385 rows, 
                Total rows to insert into "kayako"."swticketlinkedtables": 22385
        --[pipeData]  For now inserted: 34735 rows, 
                Total rows to insert into "kayako"."swticketlocks": 34735
        --[loadData] Loading the data...
        --[loadData] Loading the data...
        --[loadData] Loading the data...
        --[loadData] Loading the data...
        --[loadData] Loading the data...
        --[loadData] Loading the data...
        --[loadData] Loading the data...

So far as I can tell all the data transferred.  There is no file nmig/logs_directory/errors-only.log

**Comment by AnatolyUss** [comment] 2019-04-13 20:28
Hi,
The issue seems to be fixed in a new version (4.0.0), that I've released yesterday.
Sorry, for the delay.
@snblitz  and @Boshen , many thanks for your collaboration!

**Comment by snblitz** [comment] 2019-04-18 00:54
I ran version 4.0.0 today and it completed **without** the infinite loop.  :)

**Closed** 2019-04-18 00:55 UTC
