### ISSUE TITLE
Hanging with no output

### ISSUE THREAD

**Issue by danports** [AnatolyUss/nmig#73] opened 2020-05-31 16:17 UTC
I started nmig 15-20 minutes ago and this is all the output that I have:

```
# npm start

> nmig@5.2.0 start /nmig/nmig-master
> node dist/src/Main.js
```

Is this normal? I was expecting a bit more output. The process isn't using much or any CPU, and I don't see any log files.

**Comment by ALERTua** [comment] 2020-06-29 16:50
same here.
Windows 10

**Comment by AnatolyUss** [comment] 2020-07-06 16:28
Hello,
Honestly, I struggle to reproduce this issue using both Windows 10 and MacOS.
Which version of Node.js are you using (Node.js >=10 is required)?
Are there any additional output on the screen?
Are there any logs? (<code>/path/to/nmig/logs_directory</code>)

**Comment by GDrupal** [comment] 2020-08-04 22:58
I have a similar error Trying to configure this app inside a docker container, it's like not doing anything... neither failing... just hanging there. It was complaining about wrong config, on reachable mysql etc, I fixed that it seems to be bale to conect but nothing happens.
It ask to proceed, then nothing
`pp_node       | 	--[boot] Configuration has been just loaded.
pp_node       | 	--[boot] NMIG is ready to start. 
pp_node       | 	--[boot] Proceed? [Y/n]
Y
`

**Comment by AnatolyUss** [comment] 2020-08-10 18:17
Hello @GDrupal ,
I didn't try to run Nmig via Docker.
Could you share your Docker configuration, please?

**Comment by danports** [comment] 2020-08-10 18:28
FWIW, I had to put my migration project on the back burner and can't recall all of the details now (e.g. whether I was using an nmig-specific image or just a generic Node.js image), but I believe I was also running nmig via Docker when I first encountered this issue.

**Comment by alexthamm** [comment] 2020-09-30 17:18
Hi, I observed the behavior @danports described when I configured a HTTP port of another application instead of the PostgreSQL port.

**Comment by danports** [comment] 2020-10-26 00:10
I tried running the latest version of nmig (v5.4.0) today and was unable to reproduce this issue under the `node:latest` Docker image.

**Comment by AnatolyUss** [comment] 2020-10-30 00:09
Hi,
Could you try the latest Nmig version (<code>v5.5.0</code>), please?

**Comment by AnatolyUss** [comment] 2022-02-19 18:28
Closing this issue, as it seems not reproducible.

**Closed by AnatolyUss** 2022-02-19 18:28 UTC

**Comment by danports** [comment] 2022-02-19 20:30
No worries, I put my database migration project on the back burner, but if I get back to it, I'll let you know if I run into this again.
